name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Backend Docker Image
        run: |
          docker build -t my-backend ./backend

      - name: Build Frontend Docker Image
        run: |
          docker build -t my-frontend ./frontend
