# This GitHub Actions workflow is designed to automate the process of importing SBOM (Software Bill of Materials) and Vulnerability Reports into OWASP Dependency-Track whenever a commit is pushed to 
# the main branch or when manually triggered using workflow_dispatch
name: Import SBOM & Vulnerability Reports to Dependency-Track

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  import-to-dependency-track:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Upload SBOM to Dependency-Track
        run: |
        # -H "Authorization: Bearer ${{ secrets.DT_API_KEY }}": The Authorization header is required for 
        # authenticating the API request. It uses a Bearer token stored in GitHub Secrets (DT_API_KEY).
        # The API key is a secure way to authenticate without exposing sensitive information.
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.DT_API_KEY }}" \
            -F "file=@sbom.json" \
            ${{ secrets.DT_URL }}/api/v1/bom

      - name: Upload Vulnerability Report to Dependency-Track
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.DT_API_KEY }}" \
            -F "file=@vulnerability-report.json" \
            ${{ secrets.DT_URL }}/api/v1/bom
